spring:
  config:
    activate:
      on-profile: "dev"

  jpa:
    hibernate:
      ddl-auto: none

server:
  servlet:
    session:
      cookie:
        name: SESSION
        same-site: none
        secure: true