spring:
  config:
    activate:
      on-profile: "security"

  kakao:
    clinet-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: "${BASE_URL}/api/auth/kakao/callback"
    token-uri: "https://kauth.kakao.com/oauth/token"
    user-info-uri: "https://kapi.kakao.com/v2/user/me"