name: develop pull request Check and Test

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # JDK 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradlew 생행 권한 허용
      - name: Grant Execute Permission for Gradlew
        run: chmod +x ./gradlew

      # .env 파일 생성
      - name: Create .env file
        run: |
          echo "${{ secrets.ENV }}" >> .env
          
      # .env 파일을 로드하고 환경변수로 등록
      - name: Load .env and Export Environment Variable
        run: |
          set -o allexport
          source .env
          set +o allexport

      # Gradle setup, check(코드 품질 관리, 테스트) 실행
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}